### ISSUE TITLE
Logo in Hebrew??

### ISSUE THREAD

**Issue by mosheavni** [marreman/tsen-magenta-yellow#2]
The logo is written in Hebrew, but it's written backwards:
ןעצ
is supposed to be:
צען
and also in the native tongue, you'd lose the ע, so it would be written best as:
צן

BTW, why??? 🤣

**Comment by marreman** [comment]
Haha! I just looked for an interesting name and logo. I was looking at the Duo color schemes. So duo means two, but I had ten colors. Maybe translate it to some other language, I thought. And then: Oh such beautiful characters in the Hebrew alphabet. That's the story. :D

Thanks for the enlightenment! :)
